services:
    eliza:
        command: ["pnpm", "start", "--character=./characters/eve.character.json"]
        build:
            context: .
            dockerfile: Dockerfile
        stdin_open: true
        tty: true
        volumes:
            - ./data:/app/data
        environment:
            - DISCORD_APPLICATION_ID=
            - DISCORD_API_TOKEN=
            - GROK_API_KEY=
            - ELEVENLABS_XI_API_KEY=
            - ELEVENLABS_MODEL_ID=eleven_multilingual_v2
            - ELEVENLABS_VOICE_ID=21m00Tcm4TlvDq8ikWAM
            - ELEVENLABS_VOICE_STABILITY=0.5
            - ELEVENLABS_VOICE_SIMILARITY_BOOST=0.9
            - ELEVENLABS_VOICE_STYLE=0.66
            - ELEVENLABS_VOICE_USE_SPEAKER_BOOST=false
            - ELEVENLABS_OPTIMIZE_STREAMING_LATENCY=4
            - ELEVENLABS_OUTPUT_FORMAT=pcm_16000
            - SERVER_PORT=3000
            - HEDERA_PRIVATE_KEY=
            - HEDERA_ACCOUNT_ID=
            - HEDERA_NETWORK_TYPE=
            - HEDERA_KEY_TYPE=
        ports:
            - "3000:3000"
        restart: always
